version: '3.8'
services:
  postgresdb:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - db_data_pg:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: HariNurd
      POSTGRES_PASSWORD: harinurdnerd0410
      POSTGRES_DB: load_db
    networks:
      - pg_network

  mysqldb:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - db_data_mysql:/var/lib/mysql
    environment:
      MYSQL_USER: HariNurd
      MYSQL_PASSWORD: harinurdnerd0410
      MYSQL_ROOT_PASSWORD: super-secret-pw
      MYSQL_DATABASE: extract-db
    networks:
      - mysql_network

volumes:
  db_data_pg:
  db_data_mysql:

networks:
  pg_network:
  mysql_network:
